# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '11.0'

# target 'ReactNativeIntegration' do
#   # Wrapping the use_native_modules! in a block
#   begin
#     use_native_modules!
#   rescue => exception
#     puts "Error loading native modules: #{exception}"
#   end

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # to enable hermes on iOS, change `false` to `true` and then install pods
#     :hermes_enabled => false
#   )

#   pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'

#   target 'ReactNativeIntegrationTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable the next line.
#   use_flipper!()

#   post_install do |installer|
#     react_native_post_install(installer)
#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
#     installer.pods_project.targets.each do |target|
#         target.build_configurations.each do |config|
#           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
#          end
#         case target.name
#           when 'RCT-Folly'
#             target.build_configurations.each do |config|
#               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#             end
#           end
#       end
#   end
  
#   #target 'NotificationService' do
#     # Pods for NotificationService
#    # pod 'CTNotificationService'
#    # pod "CleverTap-iOS-SDK"
#   # end
  
#   target 'NotificationContentDemo' do
#     pod 'CTNotificationContent'
#     pod "CleverTap-iOS-SDK"
#   end
  
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ReactNativeIntegration' do
  # Wrapping use_native_modules! inside a begin-rescue block
  begin
    use_native_modules!
  rescue => exception
    puts "Error with native modules: #{exception.message}"
  end

  use_react_native!(
    :path => '../node_modules/react-native',
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  
  pod 'OpenSSL-Universal', '1.1.180'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

  
  target 'ReactNativeIntegrationTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper' => '0.99.0' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end

  #target 'NotificationService' do
    # Pods for NotificationService
    # pod 'CTNotificationService'
    # pod "CleverTap-iOS-SDK"
  #end

  target 'NotificationContentDemo' do
    pod 'CTNotificationContent'
    pod "CleverTap-iOS-SDK"
  end
end
